# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York"
    TERM: dumb
version: 2
jobs:
  test:
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.lock" }}
      - run:
          name: Startup checks
          command: |
            sudo docker --version
            sudo docker-compose --version
            lsb_release -a
            export -p
      - run:
          name: Get Lando
          command: |
            sudo apt-get update
            sudo apt-get install cgroup-bin -y
            if [ ! -f /tmp/lando-latest.deb ]; then
              curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
            fi
            sudo dpkg -i /tmp/lando-latest.deb
            lando version
      - run:
          name: Setup Lando
          command: |
            lando start
      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - "vendor"
            - /tmp/lando-latest.deb
      - run:
          name: Test Lando
          command: |
            lando composer test

workflows:
  version: 2
  deployment:
    jobs:
      - test
